version: '3.8'
services:
  django-atlantis-dark:
    container_name: django-atlantis-dark
    build: './django-atlantis-dark'
    restart: always
    networks:
      - web_network

  django-pixel:
    container_name: django-pixel
    build: './django-pixel'
    restart: always
    networks:
      - web_network

  nginx:
    container_name: nginxservproxy
    image: nginx:alpine-slim
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
