version: '3.8'
services:
#Premier conteneur
  django-atlantis-dark:
    container_name: django-atlantis-dark #nom de notre conteneur
    build: './django-atlantis-dark' #Emplacement des fichiers de configuration 
    restart: always
    networks:
      - web_network

  django-pixel: #Seconde app
    container_name: django-pixel #Nom du conteneur
    build: './django-pixel' #Emplacement des fichiers de configuration
    restart: always
    networks:
      - web_network

  django-material-kit: #Troisieme app
    container_name: django-material-kit #Nom du conteneur
    build: './django-material-kit' #Emplacement des fichiers de configuration
    restart: always
    networks:
      - web_network

  flask-material-dashboard: #Troisieme app
    container_name: flask-material-dashboard #Nom du conteneur
    build: './flask-material-dashboard' #Emplacement des fichiers de configuration
    restart: always
    networks:
      - web_network
      
  #reverse proxy
  nginx:
    container_name: nginxservproxy
    image: nginx:alpine-slim #utilisation d'une image slime pour l'optimisation
    restart: always
    volumes: #Création d'un volume pour la persistance des données
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:8080" #Port app 1
      - "8081:8081" #Port app 2
      - "99:99"     #Port app 3
      - "5005:5005" #Port app 4
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
