version: '3.8'
services:
  appseed-app:
    container_name: django-pixel
    restart: always
    build: .
    networks:
      - web_network
    expose:
      - "8081"
networks:
  web_network:
    driver: bridge
