version: '3.8'
services:
  appseed-app:
    container_name: django-atlantis-dark
    restart: always
    build: .
    networks:
      - web_network
    expose:
      - "8080"

networks:
  web_network:
    driver: bridge
